import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Download, IndianRupee, TrendingUp, AlertCircle, Loader, RefreshCw } from 'lucide-react';
import API from '../../utils/axiosHelper';
import toast from 'react-hot-toast';

const Payroll = () => {
  const [payrolls, setPayrolls] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Function to fetch data (extracted so we can reuse it)
  const fetchPayroll = async (isBackground = false) => {
    try {
      if (!isBackground) setLoading(true); // Only show spinner on first load
      else setIsRefreshing(true); // Show small refresh icon on background updates

      const { data } = await API.get('/payroll/my-history');
      setPayrolls(data);
    } catch (error) {
      console.error("Payroll fetch error:", error);
      // Don't toast on background errors to avoid spamming the user
      if (!isBackground) toast.error('Could not load payroll history');
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  };

  // 1. Setup Live Polling
  useEffect(() => {
    // Initial Load
    fetchPayroll();

    // 🔄 POLL EVERY 5 SECONDS
    const intervalId = setInterval(() => {
      fetchPayroll(true); // Pass true to indicate background fetch
    }, 5000);

    // Cleanup when leaving the page
    return () => clearInterval(intervalId);
  }, []);

  const handleDownload = (record) => {
    const slipContent = `
      PAYSLIP FOR: ${record.month}
      ---------------------------------
      Basic Salary: Rs. ${record.basicSalary.toLocaleString('en-IN')}
      Allowances:   Rs. ${record.allowances.toLocaleString('en-IN')}
      Deductions:  -Rs. ${record.deductions.toLocaleString('en-IN')}
      ---------------------------------
      NET PAY:      Rs. ${record.netPay.toLocaleString('en-IN')}
      ---------------------------------
      Increment Applied: ${record.increment || 0}%
      Generated by EMS Nexus
    `;

    const blob = new Blob([slipContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Payslip_${record.month.replace(' ', '_')}.txt`);
    
    document.body.appendChild(link);
    link.click();
    link.parentNode.removeChild(link);
    
    toast.success(`Downloaded payslip for ${record.month}`);
  };

  const totalNetPay = payrolls.reduce((acc, curr) => acc + curr.netPay, 0);
  const lastIncrement = payrolls.length > 0 ? (payrolls[0].increment || 0) : 0;

  if (loading) {
    return (
      <div className="d-flex justify-content-center align-items-center" style={{minHeight: '400px'}}>
        <Loader className="animate-spin text-primary" size={32} />
      </div>
    );
  }

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }} 
      animate={{ opacity: 1, y: 0 }} 
      className="container-fluid p-0"
    >
      {/* Header with Live Indicator */}
      <div className="d-flex justify-content-between align-items-center mb-4">
         <div>
            <h3 className="fw-bold text-dark mb-1">My Payroll</h3>
            <p className="text-muted mb-0">Manage your salary and payslips.</p>
         </div>
         {isRefreshing && (
            <span className="text-muted small d-flex align-items-center gap-2">
               <RefreshCw size={14} className="animate-spin"/> Updating live...
            </span>
         )}
      </div>

      {/* Salary Overview Cards */}
      <div className="row g-4 mb-4">
        <div className="col-md-6 col-lg-4">
          <div className="card bg-dark text-white p-4 border-0 shadow" style={{background: 'linear-gradient(145deg, #1e293b, #0f172a)'}}>
            <div className="d-flex justify-content-between">
              <div>
                <p className="text-white-50 small text-uppercase fw-bold mb-1">Total Net Pay (YTD)</p>
                <h2 className="fw-bold mb-0">₹ {totalNetPay.toLocaleString('en-IN')}</h2>
              </div>
              <div className="bg-white bg-opacity-10 p-2 rounded">
                 <IndianRupee className="text-white"/>
              </div>
            </div>
          </div>
        </div>
        <div className="col-md-6 col-lg-4">
          <div className="card p-4 border-0 shadow-sm">
             <div className="d-flex justify-content-between">
              <div>
                <p className="text-muted small text-uppercase fw-bold mb-1">Last Increment</p>
                <h2 className="fw-bold mb-0 text-success">+ {lastIncrement}%</h2>
              </div>
              <div className="bg-success-subtle p-2 rounded">
                 <TrendingUp className="text-success"/>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Payslip Table */}
      <div className="card border-0 shadow-sm">
        <div className="card-header bg-white py-3 border-bottom">
           <h5 className="fw-bold mb-0">Payslip History</h5>
        </div>
        <div className="table-responsive">
           <table className="table table-hover align-middle mb-0">
              <thead className="bg-light">
                 <tr>
                    <th className="ps-4 py-3 border-0 text-muted small fw-bold text-uppercase">Month</th>
                    <th className="py-3 border-0 text-muted small fw-bold text-uppercase">Basic Salary</th>
                    <th className="py-3 border-0 text-muted small fw-bold text-uppercase">Allowances</th>
                    <th className="py-3 border-0 text-muted small fw-bold text-uppercase">Deductions</th>
                    <th className="py-3 border-0 text-muted small fw-bold text-uppercase">Net Pay</th>
                    <th className="pe-4 py-3 border-0 text-end text-muted small fw-bold text-uppercase">Action</th>
                 </tr>
              </thead>
              <tbody>
                 {payrolls.length === 0 ? (
                    <tr>
                       <td colSpan="6" className="text-center py-5 text-muted">
                          <AlertCircle className="mb-2 opacity-25" size={32} />
                          <p className="mb-0">No payslips found.</p>
                       </td>
                    </tr>
                 ) : (
                    payrolls.map((record) => (
                      <tr key={record._id}>
                        <td className="ps-4 fw-bold">{record.month}</td>
                        <td className="text-muted">₹ {record.basicSalary.toLocaleString('en-IN')}</td>
                        <td className="text-muted">₹ {record.allowances.toLocaleString('en-IN')}</td>
                        <td className="text-danger">- ₹ {record.deductions.toLocaleString('en-IN')}</td>
                        <td className="fw-bold text-success">₹ {record.netPay.toLocaleString('en-IN')}</td>
                        <td className="pe-4 text-end">
                          <button 
                            onClick={() => handleDownload(record)} 
                            className="btn btn-sm btn-outline-dark d-inline-flex align-items-center gap-2 hover-shadow"
                          >
                             <Download size={14} /> Download
                          </button>
                        </td>
                      </tr>
                    ))
                 )}
              </tbody>
           </table>
        </div>
      </div>
    </motion.div>
  );
};

export default Payroll;